#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/sonaremin/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# the following is only required if we run via xpra
if [ "$(ps auxwww | grep /usr/bin/xpra | grep -v grep)" != "" ]; then

  # read the actual config info file if it exists
  if [ -f /data/config/info.txt ]; then
    . /data/config/info.txt
  fi

  # the xorgxrdp approach for mesa requires to set a proper resolution here now
  if [ "$SYSTEM_MODEL" = "raspberrypi" ]; then
    MY_HDMI=`ls /sys/class/drm | grep HDMI | head -n 1 | sed 's,.*HDMI,HDMI,g;s,-.-,-,g'`
    xrandr --output $MY_HDMI --mode 1024x768
    sleep 3
  fi

# the following is only required if we do not run via xpra
else

  # read the actual sonaremin config file if it exists
  if [ -f /data/config/sonaremin.txt ]; then
    . /data/config/sonaremin.txt
  fi

  # if we define a default keyboard language then set it here
  if [ "$XKB_LANGUAGE" != "" ]; then
    setxkbmap $XKB_LANGUAGE
  fi

fi

/home/sonaremin/bin/start-qjackctl.sh &
/home/sonaremin/bin/start-vcvrack.sh &
/home/sonaremin/bin/start-local.sh &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

#exec fluxbox
# or if you want to keep a log:
exec fluxbox -log "/home/sonaremin/.fluxbox/log"
